### ISSUE TITLE
Add a more descriptive report file name

### ISSUE THREAD

**Issue by ameliav** [cisagov/tpt-reports#28]
# 💡 Summary #

Add a more descriptive output file name.

## Motivation and context ##

This would be useful because the current output name is non-descriptive and non-specific and will not be able to be differentiated from other reports generated.

## Implementation notes ##

Current file name: TPT_Report.pdf
Example of future naming convention: TPT_Report_YYYY-MM-DD_[ASSESSMENT_ID].pdf

## Acceptance criteria ##

How do we know when this work is done?

- [x] Sign off from Fed Lead on the new naming convention
- [x] https://github.com/cisagov/tpt-reports/issues/30 is completed
- [ ] Update report file name

**Comment by schmelz21** [comment]
@MinaSalehi , @jthough9 , @jennythompson8675309 - can we begin to confirm with federal team with how we want the filenames to be when a report is generated. See Implementation notes.

**Comment by jennythompson8675309** [comment]
I like "TPT_Report_[TODAYS_DATE]_[SERVICENOW_ID].pdf"
I'd probably specify how we'd format the date when we ask Anna to approve the name format. Probably YYYYMMDD?

**Comment by ameliav** [comment]
@schmelz21 please let me know when the format is decided. Once it is, I'll create a branch for the changes.

**Comment by schmelz21** [comment]
While in review, please note the blocker - https://github.com/cisagov/tpt-reports/issues/30

**Comment by ameliav** [comment]
Received sign off for the naming convention by Fed Lead. Added blocker issue https://github.com/cisagov/tpt-reports/issues/30 as additional acceptance criteria.
