### ISSUE TITLE
Update README.md and Project Description

### ISSUE THREAD

**Issue by schmelz21** [cisagov/tpt-reports#3]
# 💡 Summary #

Add project scope, requirements, instillation and run instructions in README.md.

## Motivation and context ##

Information will allow a new developer spin up application when cloned.

## Implementation notes ##

Please provide details for implementation, such as:

- Update README.md
- Add a Github Description

## Acceptance criteria ##

How do we know when this work is done?

- [x] GitHub Description update
- [x] Project Scope added
- [x] Application Requirements added
- [x] Install Instructions provided
- [x] Run Instructions added

**Comment by schmelz21** [comment]
for reference - passed PR - https://github.com/cisagov/pe-reports

**Comment by ameliav** [comment]
Using the pe-reports reference, I replicated as much of it as I could, verified with another dev member the info presented is correct, and pushed it up to staging in commit: ba4339eec85c95ad7a82ff18c8a1f3093646ebdd
