### ISSUE TITLE
Validate DOMAIN_TESTED argument inputs

### ISSUE THREAD

**Issue by schmelz21** [cisagov/tpt-reports#36]
# 💡 Summary #

At a minimum, validate that the argument submitted that its syntax is a domain. Possibly consider the value of actually validating the domain entered existences. 

## Motivation and context ##

Validating `DOMAIN_TESTED` syntax improves quality control of the TPT report service and validating its existence and possibly gathering other relevant data may help improve upon the report content. 

## Implementation notes ##

- Research and select a validation option

## Acceptance criteria ##

How do we know when this work is done?

- [x] Only validated domains will be accepted

**Comment by schmelz21** [comment]
@jthough9 , @jennythompson8675309 , @MinaSalehi  - We are looking for emails/domains to test against. Can any of you get a list of our Group 4 and share it in Teams.

**Comment by jennythompson8675309** [comment]
Email addresses for Group 4 POCs shared in Teams.

**Comment by schmelz21** [comment]
It was determined in PR https://github.com/cisagov/tpt-reports/pull/37 string validation for "email domain" is the only requirement at this time. Any "email domain" lookup service is considered out of scope.
