### ISSUE TITLE
Add ReportLab code and library

### ISSUE THREAD

**Issue by schmelz21** [cisagov/tpt-reports#4]
# 💡 Summary #

Add ReportLab library to create output in PDF format.

## Motivation and context ##

Provides functionality to the application which produces output.

## Implementation notes ##

Please provide details for implementation, such as:

- update `setup.py` to install ReportLab
- create code for `src/tpt_report/reportlab_generator.py`
- create folder for `src/tpt_report/assets`
- update cmd for designation inputs and outputs

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Successful Install
- [ ] Pre-commits pass
- [ ] Report PDF is created
- [ ] Merge with develop

**Comment by JCantu248** [comment]
ReportLab added to setup.py. Installation works fine and all other implementation details are complete.

**Comment by schmelz21** [comment]
@JCantu248 I am going to move this back into progress. The intent was to go through a pull request with 'develop' branch after the 'first-commits' were merged. I updated the criteria.
