### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by schmelz21** [cisagov/tpt-reports#5]
# 💡 Summary #

Update `.gitIgnore` to ensure critical files are not added to GitHub repository.

## Motivation and context ##

Provides a layer of quality control.

This would be useful because...

## Implementation notes ##

- add 
```
*.log
*.pdf
*.json
```

## Acceptance criteria ##

How do we know when this work is done?

- [ ] `.gitIgnore` updated

**Comment by nickviola** [comment]
This was added in this commit: bf060c6c2722f817d04f3fe152e3b53bd86a52b2. Once #15 is merged, we can close this issue and move to the "Done" column in the TPT Reports project board.
