### ISSUE TITLE
Add tests for exception handling for load_json_file()

### ISSUE THREAD

**Issue by JCantu248** [cisagov/tpt-reports#60]
# 💡 Summary #

Add a test case to verify the exception handler in load_json_file()

## Motivation and context ##

This is needed to verify our exception handling code is correct. 

## Implementation notes ##

Please provide details for implementation, such as:

Add a test case that passes in a non-existent file and verify the exception is caught in the except block.

## Acceptance criteria ##

Work is finished when a test for the exception handling is added and all pytest cases are successful.

**Comment by schmelz21** [comment]
Completed in Release 1.0.0.
