### ISSUE TITLE
Update parser to new .json output

### ISSUE THREAD

**Issue by jthough9** [cisagov/tpt-reports#66]
# Summary #

The RPT team has updated payload scripts which produces a new format to the output files. To create reports, the app parser needs to be modified for the new format.

## Implementation notes ##

- Obtain the new .json file from a PCA Analysts
- Modify parsing process

## Acceptance criteria ##

- [x] Parser updated
- [x] Report Generates with no errors.

**Comment by schmelz21** [comment]
Currently marked "needs info", to find out if this is a one-time occurrence or we need to develop a solution.

**Comment by JCantu248** [comment]
Just to confirm, we are wanting changes made to TPT-Reports to satisfy the parsed data in sharepoint.

**Comment by jthough9** [comment]
@JCantu248 that is correct

**Comment by schmelz21** [comment]
https://github.com/cisagov/tpt-reports/pull/69

**Comment by schmelz21** [comment]
closed pr - https://github.com/cisagov/tpt-reports/pull/69
