### ISSUE TITLE
Update cyhy-pca, li-pca GitHub groups

### ISSUE THREAD

**Issue by schmelz21** [cisagov/tpt-reports#8]
# 💡 Summary #

PCA groups need updated, so to manage this project in GitHub.

## Motivation and context ##

The group members are out of date and need revised. Secondarily, create both "Read Only" and "Admin" status.

## Implementation notes ##

- get admin rights for https://github.com/orgs/cisagov/teams/cyhy-pca
- Gather list of GitHub accounts on PCA team
- Assign "Read Me" Status to appropriete accounts
- Possibly rename "li-pca" group to "pca-dev"??

## Acceptance criteria ##

How do we know when this work is done?

- [ ] All PCA Team Members are able to access GitHub Projects for TPT Reports

**Comment by schmelz21** [comment]
@nickviola - https://github.com/fisma-ready/github - Standards for creating GitHub accounts for our Analysts who don't have them. We want to assign Read Status for now...

**Comment by nickviola** [comment]
@dav3r or @jsf9k it seems that we don't have access to update group members for https://github.com/orgs/cisagov/teams/cyhy-pca/members. Is it possible for someone on our team to get access to modify this or should we provide an updated list of members? Thanks in advance.

**Comment by dav3r** [comment]
@nickviola Please have a Fed let us know which users should be given "Maintainer" role for the cyhy-pca GH team and we will set up that access, then those maintainers will be able to manage group membership.

**Comment by nickviola** [comment]
> @nickviola Please have a Fed let us know which users should be given "Maintainer" role for the cyhy-pca GH team and we will set up that access, then those maintainers will be able to manage group membership.

Perfect! I'll work on that now. Thank you

**Comment by jennythompson8675309** [comment]
Created an account: [jennythompson8675309](https://github.com/jennythompson8675309)

**Comment by nickviola** [comment]
@dav3r Sorry to bother you again. We have the Analysts on the team creating GH accounts and would like to add them to the cyhy-pca team mentioned above. We have the ability to do that now, but it seems that they first need to be added to the cisagov organization. Do you have any instruction on how we go about getting them added? Thanks in advance for your help.

**Comment by dav3r** [comment]
I have an email from @kae6114 requesting access for some folks, so it looks like this will be handled via email.
